# Generated by Django 3.0 on 2020-01-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_addstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdid', models.IntegerField(default=0, unique=True)),
                ('admno', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.IntegerField(default=0)),
                ('admdate', models.DateField(max_length=20)),
                ('guardian', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
