# Generated by Django 3.0 on 2020-01-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20200107_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='facultys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factid', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=30)),
                ('mobile', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=20)),
                ('assignedatch', models.CharField(max_length=30)),
            ],
        ),
    ]
