# Generated by Django 3.0 on 2020-01-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='stdleave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('to', models.CharField(max_length=10)),
                ('leavereason', models.CharField(max_length=20)),
                ('from_date', models.DateField(max_length=20)),
                ('to_date', models.DateField(max_length=20)),
            ],
        ),
    ]
