# Generated by Django 3.0 on 2020-01-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20200109_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstudent',
            old_name='username',
            new_name='name',
        ),
    ]
